// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "029b056b-8fc4-4de9-af26-2c6bb3729785";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onValChange();

int motionVal;
int soundVal;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(motionVal, READWRITE, ON_CHANGE, onValChange);
  ArduinoCloud.addProperty(soundVal, READWRITE, ON_CHANGE, onValChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
